In [1]:
print("hwsds")

hwsds


In [2]:
import numpy as np
import cv2
import base64

In [3]:
# 1. The Raw AI Output (Tiny 2x2 mask)
mask = np.array([
    [0, 1],
    [1, 0]
])

In [5]:
mask

array([[0, 1],
       [1, 0]])

In [4]:
# Multiply by 255 to make the water pure white
mask_visual = (mask * 255).astype(np.uint8)
print("1. Mask Visual Matrix:\n", mask_visual)

1. Mask Visual Matrix:
 [[  0 255]
 [255   0]]


In [6]:
# 2. OpenCV Encoding
success, buffer = cv2.imencode('.png', mask_visual)
print("\n2. Success Flag:", success)
print("3. Buffer (First 15 numbers):", buffer[:15])


2. Success Flag: True
3. Buffer (First 15 numbers): [137  80  78  71  13  10  26  10   0   0   0  13  73  72  68]


In [8]:
buffer

array([137,  80,  78,  71,  13,  10,  26,  10,   0,   0,   0,  13,  73,
        72,  68,  82,   0,   0,   0,   2,   0,   0,   0,   2,   8,   0,
         0,   0,   0,  87, 221,  82, 248,   0,   0,   0,  14,  73,  68,
        65,  84,   8,  29,  99, 100, 248, 207, 248, 159,  17,   0,   6,
        10,   2,   2, 157,  62, 129,  85,   0,   0,   0,   0,  73,  69,
        78,  68, 174,  66,  96, 130], dtype=uint8)

In [7]:
# 3. Base64 Translation
mask_base64 = base64.b64encode(buffer).decode('utf-8')
print("\n4. Final Base64 String:\n", mask_base64)


4. Final Base64 String:
 iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAAAAABX3VL4AAAADklEQVQIHWNk+M/4nxEABgoCAp0+gVUAAAAASUVORK5CYII=
